[build]
command = "npx next build"
publish = ".next"

[[redirects]]
from = "/*"
to = "https://shama.pk/:splat"
status = 301
force = true
conditions = {Host = ["www.shama.pk"]}

[[plugins]]
package = "@netlify/plugin-nextjs"
