// Urdu display labels for raw English values imported from the university finder spreadsheet.
// Campus names and program names are left as-is (proper nouns / not safe to auto-translate).

// Urdu name for each university's main name. Keyed on the exact university_name string from the spreadsheet.
export const universityNameLabelsUr: Record<string, string> = {
  'Abdul Wali Khan University Mardan': 'عبدالولی خان یونیورسٹی، مردان',
  'Aga Khan University': 'آغا خان یونیورسٹی',
  'Air University, Islamabad': 'ایئر یونیورسٹی، اسلام آباد',
  'Bahauddin Zakariya University, Multan': 'بہاؤالدین زکریا یونیورسٹی، ملتان',
  'Bahria University': 'بحریہ یونیورسٹی',
  'Bahria University Islamabad': 'بحریہ یونیورسٹی، اسلام آباد',
  'CECOS University of IT and Emerging Sciences, Peshawar': 'سیکوس یونیورسٹی آف انفارمیشن ٹیکنالوجی اینڈ ایمرجنگ سائنسز، پشاور',
  'COMSATS Institute of Information Technology / COMSATS University Islamabad': 'کامسیٹس یونیورسٹی، اسلام آباد',
  'Capital University of Science and Technology': 'کیپیٹل یونیورسٹی آف سائنس اینڈ ٹیکنالوجی',
  'DHA Suffa University': 'ڈی ایچ اے صفہ یونیورسٹی',
  'Dow University of Health Sciences': 'ڈاؤ یونیورسٹی آف ہیلتھ سائنسز',
  'Emerson University Multan': 'ایمرسن یونیورسٹی، ملتان',
  'Fatima Jinnah Women University Rawalpindi': 'فاطمہ جناح ویمن یونیورسٹی، راولپنڈی',
  'Forman Christian College (A Chartered University)': 'فارمن کرسچن کالج (چارٹرڈ یونیورسٹی)',
  'Foundation University Islamabad': 'فاؤنڈیشن یونیورسٹی، اسلام آباد',
  'Gomal University, Dera Ismail Khan': 'گومل یونیورسٹی، ڈیرہ اسماعیل خان',
  'Government College University, Faisalabad': 'گورنمنٹ کالج یونیورسٹی، فیصل آباد',
  'Government College University, Lahore': 'گورنمنٹ کالج یونیورسٹی، لاہور',
  'Greenwich University': 'گرین وچ یونیورسٹی',
  'HITEC University Taxila': 'ہائیٹیک یونیورسٹی، ٹیکسلا',
  'Habib University': 'حبیب یونیورسٹی',
  'Hamdard University': 'ہمدرد یونیورسٹی',
  'Indus University': 'انڈس یونیورسٹی',
  'Institute of Business Administration Karachi': 'انسٹی ٹیوٹ آف بزنس ایڈمنسٹریشن، کراچی',
  'Institute of Business Management': 'انسٹی ٹیوٹ آف بزنس مینجمنٹ',
  'Institute of Management Sciences, Peshawar': 'انسٹی ٹیوٹ آف مینجمنٹ سائنسز، پشاور',
  'International Islamic University Islamabad': 'بین الاقوامی اسلامی یونیورسٹی، اسلام آباد',
  'Islamia College Peshawar': 'اسلامیہ کالج، پشاور',
  'Khwaja Fareed University of Engineering & Information Technology, Rahim Yar Khan':
    'خواجہ فرید یونیورسٹی آف انجینئرنگ اینڈ انفارمیشن ٹیکنالوجی، رحیم یار خان',
  'Lahore College for Women University, Lahore': 'لاہور کالج فار ویمن یونیورسٹی، لاہور',
  'Lahore Garrison University': 'لاہور گیریژن یونیورسٹی',
  'Lahore Leads University': 'لاہور لیڈز یونیورسٹی',
  'Lahore School of Economics': 'لاہور سکول آف اکنامکس',
  'Lasbela University of Agriculture, Water and Marine Sciences, Uthal':
    'لسبیلہ یونیورسٹی آف ایگریکلچر، واٹر اینڈ میرین سائنسز، اوتھل',
  'Mehran University of Engineering and Technology, Jamshoro': 'مہران یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی، جامشورو',
  'Minhaj University Lahore': 'منہاج یونیورسٹی، لاہور',
  'Mohammad Ali Jinnah University': 'محمد علی جناح یونیورسٹی',
  'Muhammad Nawaz Shareef University of Agriculture, Multan': 'محمد نواز شریف یونیورسٹی آف ایگریکلچر، ملتان',
  'Muhammad Nawaz Sharif University of Engineering & Technology, Multan':
    'محمد نواز شریف یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی، ملتان',
  'NED University of Engineering & Technology': 'این ای ڈی یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی',
  'National Textile University, Faisalabad': 'نیشنل ٹیکسٹائل یونیورسٹی، فیصل آباد',
  'National University of Computer and Emerging Sciences, Islamabad': 'نیشنل یونیورسٹی آف کمپیوٹر اینڈ ایمرجنگ سائنسز',
  'National University of Modern Languages': 'نیشنل یونیورسٹی آف ماڈرن لینگویجز',
  'National University of Sciences and Technology, Islamabad': 'نیشنل یونیورسٹی آف سائنسز اینڈ ٹیکنالوجی، اسلام آباد',
  'Quaid-e-Awam University of Engineering, Science and Technology, Nawabshah':
    'قائد عوام یونیورسٹی آف انجینئرنگ، سائنس اینڈ ٹیکنالوجی، نوابشاہ',
  'Quaid-i-Azam University Islamabad': 'قائداعظم یونیورسٹی، اسلام آباد',
  'Riphah International University, Islamabad': 'ریفاہ انٹرنیشنل یونیورسٹی، اسلام آباد',
  'SZABIST University Islamabad Campus': 'شہید ذوالفقار علی بھٹو انسٹیٹیوٹ آف سائنس اینڈ ٹیکنالوجی، اسلام آباد',
  'Shaheed Benazir Bhutto Women University, Peshawar': 'شہید بینظیر بھٹو ویمن یونیورسٹی، پشاور',
  'Sir Syed University of Engineering & Technology': 'سر سید یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی',
  'Sukkur IBA University': 'سکھر آئی بی اے یونیورسٹی',
  'The Islamia University of Bahawalpur': 'اسلامیہ یونیورسٹی، بہاولپور',
  'The Superior University, Lahore': 'سپیریئر یونیورسٹی، لاہور',
  'The University of Agriculture, Peshawar': 'زرعی یونیورسٹی، پشاور',
  'The University of Faisalabad': 'یونیورسٹی آف فیصل آباد',
  'The Women University Multan': 'ویمن یونیورسٹی، ملتان',
  'University of Agriculture, Faisalabad': 'زرعی یونیورسٹی، فیصل آباد',
  'University of Balochistan, Quetta': 'یونیورسٹی آف بلوچستان، کوئٹہ',
  'University of Central Punjab, Lahore': 'یونیورسٹی آف سنٹرل پنجاب، لاہور',
  'University of Education, Lahore': 'یونیورسٹی آف ایجوکیشن، لاہور',
  'University of Engineering and Technology, Lahore': 'یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی، لاہور',
  'University of Karachi': 'جامعہ کراچی',
  'University of Lahore, Lahore': 'یونیورسٹی آف لاہور',
  'University of Management and Technology, Lahore': 'یونیورسٹی آف مینجمنٹ اینڈ ٹیکنالوجی، لاہور',
  'University of Okara': 'یونیورسٹی آف اوکاڑہ',
  'University of Peshawar': 'جامعہ پشاور',
  'University of Turbat': 'یونیورسٹی آف تربت',
  'University of Wah': 'یونیورسٹی آف واہ',
  'University of the Punjab, Lahore': 'پنجاب یونیورسٹی، لاہور',
  'Women University Mardan': 'ویمن یونیورسٹی، مردان',
};

// English short form / commonly used abbreviation shown alongside the Urdu name.
// Falls back to the original English name when no widely recognized abbreviation exists.
export const universityShortNameEn: Record<string, string> = {
  'Abdul Wali Khan University Mardan': 'AWKUM',
  'Aga Khan University': 'AKU',
  'Air University, Islamabad': 'Air University',
  'Bahauddin Zakariya University, Multan': 'BZU',
  'Bahria University Islamabad': 'Bahria University, Islamabad',
  'CECOS University of IT and Emerging Sciences, Peshawar': 'CECOS University',
  'COMSATS Institute of Information Technology / COMSATS University Islamabad': 'COMSATS University Islamabad',
  'Capital University of Science and Technology': 'CUST',
  'DHA Suffa University': 'DSU',
  'Dow University of Health Sciences': 'DUHS',
  'Fatima Jinnah Women University Rawalpindi': 'FJWU',
  'Forman Christian College (A Chartered University)': 'FCCU',
  'Government College University, Faisalabad': 'GCUF',
  'Government College University, Lahore': 'GCU Lahore',
  'HITEC University Taxila': 'HITEC University',
  'Institute of Business Administration Karachi': 'IBA Karachi',
  'Institute of Business Management': 'IoBM',
  'Institute of Management Sciences, Peshawar': 'IM Sciences',
  'International Islamic University Islamabad': 'IIUI',
  'Khwaja Fareed University of Engineering & Information Technology, Rahim Yar Khan': 'KFUEIT',
  'Lahore College for Women University, Lahore': 'LCWU',
  'Lasbela University of Agriculture, Water and Marine Sciences, Uthal': 'LUAWMS',
  'Mehran University of Engineering and Technology, Jamshoro': 'MUET',
  'Mohammad Ali Jinnah University': 'MAJU',
  'Muhammad Nawaz Shareef University of Agriculture, Multan': 'MNS-UAM',
  'Muhammad Nawaz Sharif University of Engineering & Technology, Multan': 'MNS-UET',
  'NED University of Engineering & Technology': 'NED University',
  'National Textile University, Faisalabad': 'NTU Faisalabad',
  'National University of Computer and Emerging Sciences, Islamabad': 'FAST-NUCES',
  'National University of Modern Languages': 'NUML',
  'National University of Sciences and Technology, Islamabad': 'NUST',
  'Quaid-e-Awam University of Engineering, Science and Technology, Nawabshah': 'QUEST',
  'Quaid-i-Azam University Islamabad': 'QAU',
  'SZABIST University Islamabad Campus': 'SZABIST',
  'Shaheed Benazir Bhutto Women University, Peshawar': 'SBBWU',
  'Sir Syed University of Engineering & Technology': 'SSUET',
  'Sukkur IBA University': 'Sukkur IBA',
  'The Islamia University of Bahawalpur': 'IUB',
  'The University of Faisalabad': 'TUF',
  'University of Agriculture, Faisalabad': 'UAF',
  'University of Central Punjab, Lahore': 'UCP',
  'University of Education, Lahore': 'UE Lahore',
  'University of Engineering and Technology, Lahore': 'UET Lahore',
  'University of Karachi': 'University of Karachi',
  'University of Lahore, Lahore': 'UOL',
  'University of Management and Technology, Lahore': 'UMT',
  'University of Peshawar': 'University of Peshawar',
  'University of the Punjab, Lahore': 'Punjab University (PU)',
};

// Raw `field_group` values from the spreadsheet that are the same field under a different
// phrasing/abbreviation — collapsed to one canonical bucket. Genuinely distinct disciplines
// (Nursing, Pharmacy, Agriculture / Veterinary, Health & Pharmacy) are deliberately NOT merged.
const fieldGroupNormalization: Record<string, string> = {
  'Computer / IT': 'Computer Science & IT',
  Business: 'Business & Management',
  'Social Sciences / Liberal Arts': 'Social Sciences',
  'Arts & Humanities': 'Arts, Design & Humanities',
  Humanities: 'Arts, Design & Humanities',
  Science: 'Natural Sciences',
  Sciences: 'Natural Sciences',
  Engineering: 'Engineering / Technology',
  'Allied Health': 'Health & Allied Sciences',
  Media: 'Media & Communication',
  Medical: 'Medical & Allied Health',
  'Medical / Allied Health': 'Medical & Allied Health',
  Agriculture: 'Agriculture & Food Sciences',
  'Design / Media': 'Arts, Design & Media',
  'Architecture / Design': 'Architecture',
};

export function normalizeFieldGroup(raw: string): string {
  return fieldGroupNormalization[raw] ?? raw;
}

export const fieldGroupLabelsUr: Record<string, string> = {
  'Computer Science & IT': 'کمپیوٹر سائنس اور آئی ٹی',
  'Business & Management': 'بزنس اور مینجمنٹ',
  'Social Sciences': 'سماجی علوم',
  'Arts, Design & Humanities': 'آرٹس، ڈیزائن اور انسانیات',
  'Natural Sciences': 'قدرتی علوم',
  'Engineering / Technology': 'انجینئرنگ / ٹیکنالوجی',
  Engineering: 'انجینئرنگ',
  'Health & Allied Sciences': 'صحت اور متعلقہ علوم',
  'Media & Communication': 'میڈیا اور کمیونیکیشن',
  Other: 'دیگر',
  'Medical & Allied Health': 'طب اور متعلقہ صحت',
  'Agriculture & Food Sciences': 'زراعت اور خوراک کے علوم',
  Education: 'تعلیم',
  Law: 'قانون',
  'Arts, Design & Media': 'آرٹس، ڈیزائن اور میڈیا',
  'Arts & Humanities': 'آرٹس اور انسانیات',
  Architecture: 'آرکیٹیکچر',
  'Health & Pharmacy': 'صحت اور فارمیسی',
  'Public Policy & Administration': 'پبلک پالیسی اور انتظامیہ',
  Nursing: 'نرسنگ',
  Pharmacy: 'فارمیسی',
  'Agriculture / Veterinary': 'زراعت / ویٹرنری',
};

export const degreeLevelLabelsUr: Record<string, string> = {
  'BS/Undergraduate': 'بی ایس / انڈرگریجویٹ',
  BA: 'بی اے',
  BE: 'بی ای',
  BS: 'بی ایس',
  'BS/BE': 'بی ایس / بی ای',
  'BS/Bachelor': 'بی ایس / بیچلرز',
  'BS/LLB': 'بی ایس / ایل ایل بی',
  'BS/MBBS/BDS/Pharm-D': 'بی ایس / ایم بی بی ایس / بی ڈی ایس / فارم-ڈی',
  BScN: 'بی ایس سی نرسنگ',
  DPT: 'ڈی پی ٹی (ڈاکٹر آف فزیکل تھراپی)',
  DVM: 'ڈی وی ایم (ڈاکٹر آف ویٹرنری میڈیسن)',
  LLB: 'ایل ایل بی',
  'Pharm-D': 'فارم-ڈی',
};

export const cityLabelsUr: Record<string, string> = {
  Lahore: 'لاہور',
  Faisalabad: 'فیصل آباد',
  Islamabad: 'اسلام آباد',
  Rawalpindi: 'راولپنڈی',
  'Wah Cantt': 'واہ کینٹ',
  Taxila: 'ٹیکسلا',
  Chiniot: 'چنیوٹ',
  'Chiniot / Faisalabad': 'چنیوٹ / فیصل آباد',
  Hafizabad: 'حافظ آباد',
  'Kala Shah Kaku': 'کالا شاہ کاکو',
  Samundri: 'سموندری',
  Bahawalpur: 'بہاولپور',
  'Dera Ismail Khan': 'ڈیرہ اسماعیل خان',
  Jamshoro: 'جامشورو',
  Karachi: 'کراچی',
  Mardan: 'مردان',
  Multan: 'ملتان',
  Nawabshah: 'نوابشاہ',
  Okara: 'اوکاڑہ',
  Peshawar: 'پشاور',
  Quetta: 'کوئٹہ',
  'Rahim Yar Khan': 'رحیم یار خان',
  Sukkur: 'سکھر',
  Turbat: 'تربت',
  Uthal: 'اوتھل',
};

export const sectorLabelsUr: Record<string, string> = {
  public: 'سرکاری',
  private: 'نجی',
};

export function labelFor(map: Record<string, string>, value: string): string {
  return map[value] ?? value;
}
